# Generated by Django 4.0.3 on 2022-04-18 12:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heard_of_cryptocurrency', models.BooleanField(default=False)),
                ('purchased_cryptocurrency', models.BooleanField(default=False)),
                ('consider_valid', models.BooleanField(default=False)),
                ('advertisement_as_monetization', models.IntegerField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('mining_intensity', models.IntegerField(default=False)),
                ('performance_hits', models.IntegerField(default=False)),
                ('experience', models.IntegerField(default=False)),
                ('consider_solution', models.IntegerField(default=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=200)),
                ('age', models.IntegerField(default=False)),
                ('country', django_countries.fields.CountryField(default=False, max_length=2)),
                ('time_spent', models.CharField(default=False, max_length=10000)),
                ('total_hashes', models.CharField(default=False, max_length=10000)),
            ],
        ),
    ]
