# Generated by Django 3.1.7 on 2022-03-29 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220329_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='crypto_as_monetization',
            field=models.IntegerField(default=False, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
