# Generated by Django 3.1.7 on 2022-04-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220329_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='mining_intensity',
            field=models.IntegerField(default=False),
        ),
    ]
