# Generated by Django 3.1.7 on 2022-04-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_survey_mining_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
