# Generated by Django 3.1.7 on 2022-04-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_survey_is_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_mobile',
        ),
    ]
