# Generated by Django 3.1.7 on 2022-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_survey_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
