# Generated by Django 3.1.7 on 2022-04-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_survey_is_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='crypto_as_monetization',
            new_name='advertisement_as_monetization',
        ),
    ]
