# Generated by Django 4.0.3 on 2022-04-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220406_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=200),
        ),
    ]
